log_dir: "../models/PLBERT_ar"
mixed_precision: "fp16"
data_folder: "../datasets/wiki_phoneme/processed_dataset"
batch_size: 64
save_interval: 25000
log_interval: 500
num_process: 3
num_steps: 1000000

dataset_params:
    tokenizer: ""
    token_separator: " " # token used for phoneme separator (space)
    token_mask: "M" # token used for phoneme mask (M)
    word_separator: 3039 # token used for word separator (<formula>)
    token_maps: "token_maps_ar.pkl" # token map path
    
    max_mel_length: 512 # max phoneme length
    
    word_mask_prob: 0 # probability to mask the entire word
    phoneme_mask_prob: 0 # probability to mask each phoneme
    replace_prob: 0 # probablity to replace phonemes
    
model_params:
    vocab_size: 89
    hidden_size: 768
    num_attention_heads: 12
    intermediate_size: 2048
    max_position_embeddings: 512
    num_hidden_layers: 12
    dropout: 0.1